// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: categorys.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CategoryService service

type CategoryService interface {
	GetCategorys(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CategoryList, error)
}

type categoryService struct {
	c    client.Client
	name string
}

func NewCategoryService(name string, c client.Client) CategoryService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &categoryService{
		c:    c,
		name: name,
	}
}

func (c *categoryService) GetCategorys(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CategoryList, error) {
	req := c.c.NewRequest(c.name, "CategoryService.GetCategorys", in)
	out := new(CategoryList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CategoryService service

type CategoryServiceHandler interface {
	GetCategorys(context.Context, *CategoryRequest, *CategoryList) error
}

func RegisterCategoryServiceHandler(s server.Server, hdlr CategoryServiceHandler, opts ...server.HandlerOption) error {
	type categoryService interface {
		GetCategorys(ctx context.Context, in *CategoryRequest, out *CategoryList) error
	}
	type CategoryService struct {
		categoryService
	}
	h := &categoryServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CategoryService{h}, opts...))
}

type categoryServiceHandler struct {
	CategoryServiceHandler
}

func (h *categoryServiceHandler) GetCategorys(ctx context.Context, in *CategoryRequest, out *CategoryList) error {
	return h.CategoryServiceHandler.GetCategorys(ctx, in, out)
}
